
feign:
  okhttp:
    enabled: true
  client:
    config:
      postFeignClient:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL
        decode404: false
        encoder: com.example.SimpleEncoder
        decoder: com.example.SimpleDecoder

client:
  post:
    baseUrl: https://jsonplaceholder.typicode.com