
feign:
  okhttp:
    enabled: true
  client:
    config:
      postFeignClient:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL
        decode404: false

client:
  post:
    baseUrl: http://localhost:9091